Repository samvera/bulkrax, pull requests merged in 2022-12, with the labels that each got.

#674 importers/exporters links to not show up if bulkrax is not enabled
  app/views/hyrax/dashboard/sidebar/_bulkrax_sidebar_additions.html.erb
Labels: minor-ver, bug-fix

#680 Guard on reindex_extent assignment
  app/jobs/bulkrax/create_relationships_job.rb
Labels: minor-ver

#681 bump bulkrax to v4.4.0
  Gemfile.lock
  lib/bulkrax/version.rb
Labels: ignore-for-release

#689 Normalizing serialized data for BOM characters
  app/models/bulkrax/csv_entry.rb
  app/models/bulkrax/entry.rb
  app/models/bulkrax/oai_entry.rb
  app/models/bulkrax/rdf_entry.rb
  app/models/bulkrax/xml_entry.rb
  lib/bulkrax.rb
  spec/lib/bulkrax_spec.rb
Labels: patch-ver, bug-fix

#692 Removing ∞ silent retries of Bulkrax::ImportWorkJob
  app/jobs/bulkrax/import_work_job.rb
Labels: patch-ver, bug-fix

#693 make update remote files work for file sets
  app/controllers/bulkrax/importers_controller.rb
  app/models/concerns/bulkrax/file_factory.rb
Labels: patch-ver, bug-fix

#694 Capturing raw metadata for OAI parsing of works
  app/parsers/bulkrax/oai_dc_parser.rb
Labels: patch-ver
