Repository samvera/bulkrax, pull requests merged in 2022-03, with the labels that each got.

#428 move all export request searches to posts
  app/parsers/bulkrax/csv_parser.rb
Labels: minor-ver

#419 417 Do not stop all collections from importing when one fails
  app/models/bulkrax/csv_entry.rb
  app/parsers/bulkrax/csv_parser.rb
  spec/fixtures/csv/failed_collection.csv
  spec/parsers/bulkrax/csv_parser_spec.rb
Labels: cla-signed, bug-fix

#430 minor version bump v2.3.0
  Gemfile.lock
  lib/bulkrax/version.rb
Labels: cla-signed, ignore-for-release

#436 add rspec troubleshooting steps
  CONTRIBUTING.md
Labels: cla-signed, minor-ver

#431 fix attachment concurrency issues and order issues for child objects
  app/jobs/bulkrax/create_relationships_job.rb
  app/jobs/bulkrax/importer_job.rb
  app/jobs/bulkrax/schedule_relationships_job.rb
  app/models/bulkrax/importer.rb
  app/models/bulkrax/pending_relationship.rb
  app/models/concerns/bulkrax/import_behavior.rb
  app/parsers/bulkrax/application_parser.rb
  app/parsers/bulkrax/csv_parser.rb
  db/migrate/20220301001839_create_bulkrax_pending_relationships.rb
  db/migrate/20220301020307_add_parents_to_bulkrax_importer_runs.rb
  db/migrate/20220303212810_add_order_to_bulkrax_pending_relationships.rb
  spec/factories/bulkrax/pending_relationships.rb
  spec/factories/bulkrax_entries.rb
  spec/jobs/bulkrax/create_relationships_job_spec.rb
  spec/models/bulkrax/pending_relationship_spec.rb
  spec/test_app/db/schema.rb
Labels: cla-signed, breaking-change, bug-fix

#437 435 Add check for presence of Release Notes labels on PRs
  .github/workflows/branches.yml
  .github/workflows/release_labels.yml
  .github/workflows/test.yml
  CONTRIBUTING.md
Labels: cla-signed, ignore-for-release

#440 i424 Export parent-child relationships
  app/models/bulkrax/csv_entry.rb
  spec/factories/bulkrax_exporters.rb
  spec/models/bulkrax/csv_entry_spec.rb
Labels: cla-signed, bug-fix

#442 Restore test db schema
  spec/test_app/db/schema.rb
Labels: cla-signed, ignore-for-release

#443 remove parents column serialization in the importer run
  app/models/bulkrax/importer_run.rb
Labels: cla-signed, bug-fix

#441 i425 Export FileSet filenames (and i424 fix)
  app/models/bulkrax/csv_entry.rb
  app/models/concerns/bulkrax/export_behavior.rb
  spec/models/bulkrax/csv_entry_spec.rb
Labels: cla-signed, bug-fix

#438 collection_field_mapping removal and replacement - remove deprecation warnings
  app/factories/bulkrax/object_factory.rb
  app/jobs/bulkrax/create_relationships_job.rb
  app/jobs/bulkrax/importer_job.rb
  app/models/bulkrax/csv_entry.rb
  app/models/bulkrax/entry.rb
  app/models/bulkrax/importer.rb
  app/models/bulkrax/oai_entry.rb
  app/models/bulkrax/rdf_entry.rb
  app/models/bulkrax/xml_entry.rb
  app/models/concerns/bulkrax/has_matchers.rb
  app/models/concerns/bulkrax/import_behavior.rb
  app/models/concerns/bulkrax/importer_exporter_behavior.rb
  app/parsers/bulkrax/application_parser.rb
  app/parsers/bulkrax/bagit_parser.rb
  app/parsers/bulkrax/csv_parser.rb
  app/parsers/bulkrax/oai_dc_parser.rb
  app/parsers/bulkrax/xml_parser.rb
  lib/bulkrax.rb
  spec/factories/bulkrax_importers.rb
  spec/factories/bulkrax_object_factories.rb
  spec/fixtures/csv/good.csv
  spec/jobs/bulkrax/create_relationships_job_spec.rb
  spec/jobs/bulkrax/importer_job_spec.rb
  spec/lib/bulkrax_spec.rb
  spec/models/bulkrax/importer_spec.rb
  spec/models/bulkrax/rdf_entry_spec.rb
  spec/models/bulkrax/xml_entry_spec.rb
  spec/parsers/bulkrax/csv_parser_spec.rb
  spec/parsers/bulkrax/xml_parser_spec.rb
Labels: cla-signed, breaking-change

#445 Major version bump v3.0.0.beta1
  Gemfile.lock
  lib/bulkrax/version.rb
  spec/models/bulkrax/csv_entry_spec.rb
Labels: cla-signed, ignore-for-release

#447 Fix collection relationship importing, change export join character
  app/factories/bulkrax/object_factory.rb
  app/models/bulkrax/csv_entry.rb
  spec/jobs/bulkrax/importer_job_spec.rb
Labels: cla-signed, minor-ver

#448 Update Bulkrax to v3.0.0.beta2
  Gemfile.lock
  lib/bulkrax/version.rb
Labels: cla-signed, ignore-for-release

#449 Fix NoMethodError on ImporterRun#parents
  app/models/bulkrax/importer_run.rb
  app/models/concerns/bulkrax/import_behavior.rb
  db/migrate/20220330165510_remove_array_true_from_importer_run_parents_column.rb
  spec/models/bulkrax/csv_entry_spec.rb
  spec/models/bulkrax/importer_run_spec.rb
  spec/test_app/db/schema.rb
Labels: cla-signed, bug-fix, database-changes

#450 Update Bulkrax to v3.0.0.beta3
  Gemfile.lock
  lib/bulkrax/version.rb
Labels: cla-signed, ignore-for-release
