Repository samvera/bulkrax, pull requests merged in 2022-09, with the labels that each got.

#649 i646 - process remote files for filesets
  app/factories/bulkrax/object_factory.rb
Labels: patch-ver, bug-fix

#650 call URI.open due to deprecation warning msg
  app/factories/bulkrax/object_factory.rb
Labels: enhancement, minor-ver

#653 Naming arguments and reducing duplication in import_work_job
  app/jobs/bulkrax/import_work_job.rb
Labels: ignore-for-release

#652 Adding Bulkrax config for multi-value split/join delimiters
  app/matchers/bulkrax/application_matcher.rb
  app/models/bulkrax/csv_entry.rb
  app/parsers/bulkrax/csv_parser.rb
  lib/bulkrax.rb
  lib/generators/bulkrax/templates/config/initializers/bulkrax.rb
Labels: minor-ver
