Repository samvera/bulkrax, pull requests merged in 2022-07, with the labels that each got.

#584 Fix wiki links, remove CLA mention
  README.md
Labels: ignore-for-release

#583 548 remove bagit_zip_file_size_check
  app/models/bulkrax/entry.rb
  app/parsers/bulkrax/application_parser.rb
Labels: patch-ver

#582 Split downloads by size
  app/controllers/bulkrax/exporters_controller.rb
  app/models/bulkrax/exporter.rb
  app/models/concerns/bulkrax/export_behavior.rb
  app/parsers/bulkrax/application_parser.rb
  app/parsers/bulkrax/bagit_parser.rb
  app/parsers/bulkrax/csv_parser.rb
  app/views/bulkrax/exporters/_downloads.html.erb
  app/views/bulkrax/exporters/index.html.erb
  app/views/bulkrax/exporters/show.html.erb
  lib/tasks/bulkrax_tasks.rake
  spec/jobs/bulkrax/importer_job_spec.rb
  spec/models/bulkrax/exporter_spec.rb
  spec/parsers/bulkrax/bagit_parser_spec.rb
  spec/parsers/bulkrax/csv_parser_spec.rb
Labels: enhancement, major-ver, breaking-change

#595 566 collection metadata exporting
  app/models/bulkrax/exporter.rb
  app/parsers/bulkrax/bagit_parser.rb
  app/parsers/bulkrax/csv_parser.rb
  config/locales/bulkrax.en.yml
  spec/models/bulkrax/exporter_spec.rb
  spec/parsers/bulkrax/bagit_parser_spec.rb
Labels: enhancement, minor-ver

#592 Oai stub
  spec/features/oai_dc_importer_spec.rb
  spec/fixtures/oai/oai-pmh-ListSets.xml
  spec/jobs/bulkrax/importer_job_spec.rb
Labels: minor-ver

#597 export-child-collections
  app/models/bulkrax/exporter.rb
  app/parsers/bulkrax/bagit_parser.rb
  app/parsers/bulkrax/csv_parser.rb
  app/views/bulkrax/exporters/show.html.erb
  spec/models/bulkrax/exporter_spec.rb
  spec/parsers/bulkrax/csv_parser_spec.rb
Labels: enhancement, minor-ver

#598 update to 4.1.0
  Gemfile.lock
  lib/bulkrax/version.rb
Labels: ignore-for-release

#599 undefined-method-length-for-nil-class
  app/parsers/bulkrax/application_parser.rb
  spec/parsers/bulkrax/application_parser_spec.rb
Labels: patch-ver, bug-fix

#600 ignore-misidentified-collection-entries
  app/parsers/bulkrax/csv_parser.rb
Labels: patch-ver, bug-fix

#601 patch upgrade to version 4.1.1
  Gemfile.lock
  lib/bulkrax/version.rb
Labels: ignore-for-release

#587 add pry to dev testing
  Gemfile
  Gemfile.lock
Labels: minor-ver

#602 zip-entry-exists-error
  app/parsers/bulkrax/application_parser.rb
Labels: patch-ver, bug-fix

#596 591 fix the ImportFileSetJob
  app/jobs/bulkrax/import_file_set_job.rb
  spec/jobs/bulkrax/import_file_set_job_spec.rb
Labels: minor-ver, bug-fix

#604 escape-nil-comparisons
  app/parsers/bulkrax/csv_parser.rb
Labels: patch-ver, bug-fix

#603 avoid-ldp-gone-when-writing-files-on-export
  app/parsers/bulkrax/csv_parser.rb
Labels: patch-ver, bug-fix

#606 minor version bump to 4.2.0
  Gemfile.lock
  lib/bulkrax/version.rb
Labels: ignore-for-release

#607 ldp-gone-part-2
  app/parsers/bulkrax/csv_parser.rb
Labels: patch-ver, bug-fix

#612 611-base-path-per-tenant
  app/parsers/bulkrax/application_parser.rb
  lib/tasks/bulkrax_tasks.rake
Labels: patch-ver, bug-fix

#615 611-base-path-per-tenant-v2
  app/parsers/bulkrax/application_parser.rb
Labels: patch-ver, bug-fix

#617 update-the-bulkrax-task
  lib/tasks/bulkrax_tasks.rake
Labels: patch-ver, bug-fix

#613 611 base_path spec
  db/migrate/20220726162605_create_site.rb
  db/migrate/20220726164334_create_account.rb
  spec/parsers/bulkrax/application_parser_spec.rb
  spec/parsers/bulkrax/bagit_parser_spec.rb
  spec/parsers/bulkrax/csv_parser_spec.rb
  spec/test_app/app/models/account.rb
  spec/test_app/app/models/site.rb
  spec/test_app/db/schema.rb
Labels: enhancement, patch-ver

#618 Bug Fix (Issue #614): Fix the `path_to_files` method.
  app/parsers/bulkrax/csv_parser.rb
  spec/parsers/bulkrax/csv_parser_spec.rb
Labels: bug, patch-ver, bug-fix

#620 move migration files to test_app/db
  spec/test_app/db/migrate/20220726162605_create_site.rb
  spec/test_app/db/migrate/20220726164334_create_account.rb
Labels: patch-ver, bug-fix

#621 account-for-missing-original-file-on-export
  app/parsers/bulkrax/bagit_parser.rb
  app/parsers/bulkrax/csv_parser.rb
Labels: patch-ver, bug-fix
