Repository samvera/bulkrax, pull requests merged in 2022-06, with the labels that each got.

#541 Bagit export
  app/models/bulkrax/csv_entry.rb
  app/models/bulkrax/entry.rb
  app/models/concerns/bulkrax/export_behavior.rb
  app/parsers/bulkrax/application_parser.rb
  app/parsers/bulkrax/bagit_parser.rb
Labels: enhancement

#547 Do not spawn relationship jobs for FileSets
  app/models/concerns/bulkrax/file_set_entry_behavior.rb
Labels: bug-fix

#550 bump to version 3.3.0
  Gemfile.lock
  lib/bulkrax/version.rb
Labels: ignore-for-release

#551 Issue-544 - verify depositor presence on imported works
  app/factories/bulkrax/object_factory.rb
Labels: bug-fix

#555 GitHub PR Label action improvements
  .github/release.yml
  .github/workflows/release_labels.yml
Labels: enhancement, ignore-for-release

#552 BagitParser specs
  app/parsers/bulkrax/application_parser.rb
  spec/factories/bulkrax_exporters.rb
  spec/factories/bulkrax_importers.rb
  spec/features/bagit_exporter_spec.rb
  spec/features/bagit_importer_spec.rb
  spec/fixtures/bags/bag/metadata.csv
  spec/fixtures/bags/bag/metadata.nt
  spec/fixtures/bags/bag_of_folders/manifest-sha256.txt
  spec/fixtures/bags/bag_of_folders/tagmanifest-md5.txt
  spec/fixtures/bags/bag_of_folders/tagmanifest-sha1.txt
  spec/fixtures/bags/bag_of_folders_with_csv/bag-info.txt
  spec/fixtures/bags/bag_of_folders_with_csv/bagit.txt
  spec/fixtures/bags/bag_of_folders_with_csv/data/folder1/data/test.txt
  spec/fixtures/bags/bag_of_folders_with_csv/data/folder1/metadata.csv
  spec/fixtures/bags/bag_of_folders_with_csv/manifest-sha256.txt
  spec/fixtures/bags/bag_of_folders_with_csv/tagmanifest-md5.txt
  spec/fixtures/bags/bag_of_folders_with_csv/tagmanifest-sha1.txt
  spec/fixtures/bags/bag_of_folders_with_rdf/bag-info.txt
  spec/fixtures/bags/bag_of_folders_with_rdf/bagit.txt
  spec/fixtures/bags/bag_of_folders_with_rdf/data/folder1/data/test.txt
  spec/fixtures/bags/bag_of_folders_with_rdf/data/folder1/metadata.nt
  spec/fixtures/bags/bag_of_folders_with_rdf/manifest-sha256.txt
  spec/fixtures/bags/bag_of_folders_with_rdf/tagmanifest-md5.txt
  spec/fixtures/bags/bag_of_folders_with_rdf/tagmanifest-sha1.txt
  spec/fixtures/bags/deleted_bag/metadata.nt
  spec/fixtures/bags/folder_of_bags_with_csv/bag/bag-info.txt
  spec/fixtures/bags/folder_of_bags_with_csv/bag/bagit.txt
  spec/fixtures/bags/folder_of_bags_with_csv/bag/data/test.txt
  spec/fixtures/bags/folder_of_bags_with_csv/bag/manifest-sha256.txt
  spec/fixtures/bags/folder_of_bags_with_csv/bag/metadata.csv
  spec/fixtures/bags/folder_of_bags_with_csv/bag/tagmanifest-md5.txt
  spec/fixtures/bags/folder_of_bags_with_csv/bag/tagmanifest-sha1.txt
  spec/fixtures/bags/folder_of_bags_with_rdf/bag/bag-info.txt
  spec/fixtures/bags/folder_of_bags_with_rdf/bag/bagit.txt
  spec/fixtures/bags/folder_of_bags_with_rdf/bag/data/test.txt
  spec/fixtures/bags/folder_of_bags_with_rdf/bag/manifest-sha256.txt
  spec/fixtures/bags/folder_of_bags_with_rdf/bag/metadata.nt
  spec/fixtures/bags/folder_of_bags_with_rdf/bag/tagmanifest-md5.txt
  spec/fixtures/bags/folder_of_bags_with_rdf/bag/tagmanifest-sha1.txt
  spec/models/bulkrax/rdf_entry_spec.rb
  spec/parsers/bulkrax/bagit_parser_spec.rb
Labels: ignore-for-release

#553 Pending relationships do not cause errors when destroying Importers
  app/jobs/bulkrax/create_relationships_job.rb
  app/models/bulkrax/importer_run.rb
  app/models/bulkrax/pending_relationship.rb
  app/models/concerns/bulkrax/import_behavior.rb
  db/migrate/20220609001128_rename_bulkrax_importer_run_to_importer_run.rb
  spec/factories/bulkrax/pending_relationships.rb
  spec/models/bulkrax/importer_run_spec.rb
  spec/test_app/db/schema.rb
Labels: patch-ver, bug-fix, database-changes

#557 add new version-bump label to allowed list
  .github/workflows/release_labels.yml
Labels: enhancement, ignore-for-release

#556 patch version bump v3.3.1
  Gemfile.lock
  lib/bulkrax/version.rb
Labels: ignore-for-release, version-bump

#558 #398 Handle malformed CSV errors better
  app/jobs/bulkrax/importer_job.rb
  app/models/bulkrax/importer.rb
  spec/jobs/bulkrax/importer_job_spec.rb
Labels: patch-ver, bug-fix

#561 560 reimplement thumbnail export
  app/models/bulkrax/csv_entry.rb
  spec/models/bulkrax/csv_entry_spec.rb
Labels: patch-ver, bug-fix

#559 Do not render empty Error accordian on importers that succeed with failures
  app/models/concerns/bulkrax/status_info.rb
  spec/models/concerns/bulkrax/status_info_spec.rb
Labels: patch-ver, bug-fix

#562 patch version bump v3.3.2
  Gemfile.lock
  lib/bulkrax/version.rb
Labels: ignore-for-release, version-bump

#564 reworked bagit write files to not create empty bags
  app/parsers/bulkrax/bagit_parser.rb
Labels: ignore-for-release, bug-fix

#565 Remove willow_sword as a soft dependency, make rubyzip a full dependency
  .gitignore
  Gemfile
  Gemfile.lock
  app/parsers/bulkrax/application_parser.rb
  bulkrax.gemspec
  lib/generators/bulkrax/install_generator.rb
  spec/parsers/bulkrax/bagit_parser_spec.rb
Labels: enhancement, minor-ver

#567 566-collections-metadata-only
  app/models/bulkrax/exporter.rb
  app/parsers/bulkrax/csv_parser.rb
  app/views/bulkrax/exporters/_form.html.erb
  app/views/bulkrax/exporters/show.html.erb
  config/locales/bulkrax.en.yml
  spec/models/bulkrax/exporter_spec.rb
Labels: enhancement, minor-ver

#568 563-bagit-export-fileset-metadata
  app/parsers/bulkrax/bagit_parser.rb
  spec/parsers/bulkrax/bagit_parser_spec.rb
Labels: enhancement, minor-ver

#569 handles bagit bag file exists error and prepends id to data filenames
  app/models/concerns/bulkrax/export_behavior.rb
  app/parsers/bulkrax/bagit_parser.rb
Labels: minor-ver, bug-fix

#572 Bagit export status and total fix
  app/jobs/bulkrax/export_work_job.rb
  app/parsers/bulkrax/bagit_parser.rb
  spec/parsers/bulkrax/bagit_parser_spec.rb
Labels: minor-ver, bug-fix

#573 Fix error when migrating MySQL db (ref #393)
  db/migrate/20220609001128_rename_bulkrax_importer_run_to_importer_run.rb
Labels: patch-ver, bug-fix, database-changes

#571 563 import fileset metadata
  app/jobs/bulkrax/create_relationships_job.rb
  app/models/concerns/bulkrax/dynamic_record_lookup.rb
  app/models/concerns/bulkrax/file_set_entry_behavior.rb
  app/models/concerns/bulkrax/import_behavior.rb
  app/parsers/bulkrax/bagit_parser.rb
  app/parsers/bulkrax/csv_parser.rb
  spec/fixtures/bags/bag/metadata.csv
  spec/fixtures/bags/bag_of_folders_with_csv/bag-info.txt
  spec/fixtures/bags/bag_of_folders_with_csv/data/folder1/metadata.csv
  spec/fixtures/bags/bag_of_folders_with_csv/manifest-sha256.txt
  spec/fixtures/bags/bag_of_folders_with_csv/tagmanifest-md5.txt
  spec/fixtures/bags/bag_of_folders_with_csv/tagmanifest-sha1.txt
  spec/fixtures/bags/bag_with_csv/data/moon.jpg
  spec/fixtures/bags/bag_with_csv/manifest-sha256.txt
  spec/fixtures/bags/bag_with_csv/metadata.csv
  spec/fixtures/bags/bag_with_csv/tagmanifest-md5.txt
  spec/fixtures/bags/bag_with_csv/tagmanifest-sha1.txt
  spec/fixtures/bags/folder_of_bags_with_csv/bag/metadata.csv
  spec/fixtures/csv/files/sun.jpg
  spec/jobs/bulkrax/import_file_set_job_spec.rb
  spec/models/concerns/bulkrax/dynamic_record_lookup_spec.rb
  spec/parsers/bulkrax/bagit_parser_spec.rb
  spec/parsers/bulkrax/csv_parser_spec.rb
Labels: enhancement, minor-ver, bug-fix

#575 added required tag to form fields
  app/views/bulkrax/exporters/_form.html.erb
Labels: enhancement, minor-ver

#578 minor-version-bump-3.5.0
  Gemfile.lock
  lib/bulkrax/version.rb
Labels: ignore-for-release

#579 Only require one PR label
  .github/workflows/release_labels.yml
Labels: ignore-for-release

#580 Undo require form fields
  app/views/bulkrax/exporters/_form.html.erb
Labels: patch-ver, bug-fix

#581 release 3.5.1
  Gemfile.lock
  lib/bulkrax/version.rb
Labels: ignore-for-release
