Repository samvera/bulkrax, pull requests merged in 2022-02, with the labels that each got.

#388 Add ability to import FileSet metadata using the CSV Importer
  .rubocop_todo.yml
  Gemfile.lock
  app/controllers/bulkrax/importers_controller.rb
  app/factories/bulkrax/object_factory.rb
  app/jobs/bulkrax/create_relationships_job.rb
  app/jobs/bulkrax/import_collection_job.rb
  app/jobs/bulkrax/import_file_set_job.rb
  app/jobs/bulkrax/import_work_job.rb
  app/jobs/bulkrax/importer_job.rb
  app/models/bulkrax/csv_entry.rb
  app/models/bulkrax/csv_file_set_entry.rb
  app/models/bulkrax/importer.rb
  app/models/concerns/bulkrax/dynamic_record_lookup.rb
  app/models/concerns/bulkrax/import_behavior.rb
  app/models/concerns/bulkrax/importer_exporter_behavior.rb
  app/parsers/bulkrax/application_parser.rb
  app/parsers/bulkrax/bagit_parser.rb
  app/parsers/bulkrax/csv_parser.rb
  app/parsers/bulkrax/oai_dc_parser.rb
  app/views/bulkrax/importers/index.html.erb
  app/views/bulkrax/importers/show.html.erb
  db/migrate/20211220195027_add_file_set_counters_to_importer_runs.rb
  db/migrate/20220118001339_add_import_attempts_to_entries.rb
  db/migrate/20220119213325_add_work_counters_to_importer_runs.rb
  spec/factories/bulkrax/object_factory_spec.rb
  spec/factories/bulkrax_entries.rb
  spec/factories/bulkrax_object_factories.rb
  spec/fixtures/csv/work_with_file_sets.csv
  spec/jobs/bulkrax/create_relationships_job_spec.rb
  spec/jobs/bulkrax/import_file_set_job_spec.rb
  spec/jobs/bulkrax/import_work_job_spec.rb
  spec/models/concerns/bulkrax/dynamic_record_lookup_spec.rb
  spec/parsers/bulkrax/csv_parser_spec.rb
  spec/test_app/db/schema.rb
Labels: enhancement, cla-signed, minor-ver

#405 minor version bump 2.1.0
  Gemfile.lock
  lib/bulkrax/version.rb
Labels: cla-signed, ignore-for-release

#406 Collection title should be a string instead of an array
  app/parsers/bulkrax/csv_parser.rb
Labels: cla-signed, bug-fix

#407 patch version bump v2.1.1
  Gemfile.lock
  lib/bulkrax/version.rb
Labels: cla-signed, ignore-for-release

#390 fixes export zip downloads inline #389
  app/models/concerns/bulkrax/download_behavior.rb
Labels: bug-fix

#409 Fix test db cleaning, stop running ObjectFactory spec when it isn't supposed to be
  spec/models/bulkrax/object_factory_spec.rb
  spec/rails_helper.rb
Labels: cla-signed, bug-fix

#408 Add Collections and FileSets to CSV exports
  app/models/bulkrax/csv_file_set_entry.rb
  app/parsers/bulkrax/csv_parser.rb
  spec/factories/bulkrax_exporters.rb
  spec/parsers/bulkrax/csv_parser_spec.rb
Labels: enhancement, in progress, cla-signed, minor-ver

#410 minor version bump 2.2.0
  Gemfile.lock
  lib/bulkrax/version.rb
Labels: cla-signed, ignore-for-release

#411 call increment_counters before perform_now job
  app/parsers/bulkrax/csv_parser.rb
Labels: cla-signed, bug-fix

#413 patch version bump v2.2.1
  Gemfile.lock
  lib/bulkrax/version.rb
Labels: cla-signed, ignore-for-release

#414 i350 - fix for multile ui elements on index page
  app/views/bulkrax/exporters/index.html.erb
  app/views/bulkrax/importers/index.html.erb
Labels: cla-signed, bug-fix

#418 patch version bump v2.2.2
  Gemfile.lock
  lib/bulkrax/version.rb
Labels: cla-signed, ignore-for-release

#416 Show all added cloud files, not first ten
  app/assets/javascripts/bulkrax/importers.js.erb
Labels: cla-signed, bug-fix

#420 i421 - enqueued entries count bug
  app/models/concerns/bulkrax/importer_exporter_behavior.rb
Labels: cla-signed, bug-fix

#422 patch version bump 2.2.3
  Gemfile.lock
  lib/bulkrax/version.rb
  spec/jobs/bulkrax/importer_job_spec.rb
Labels: cla-signed, ignore-for-release

#423 fix visibility so it gets respected when importing
  app/models/bulkrax/csv_entry.rb
  app/models/concerns/bulkrax/has_matchers.rb
Labels: cla-signed, bug-fix

#426 patch version bump v2.2.4
  Gemfile.lock
  lib/bulkrax/version.rb
Labels: cla-signed, ignore-for-release
