Repository samvera/bulkrax, pull requests merged in 2022-08, with the labels that each got.

#619 195 -fix browse everything button
  app/assets/javascripts/bulkrax/importers.js.erb
  app/views/bulkrax/importers/edit.html.erb
  app/views/bulkrax/importers/new.html.erb
Labels: bug, patch-ver, bug-fix

#542 444-exporter-show-page
  app/controllers/bulkrax/exporters_controller.rb
  app/views/bulkrax/exporters/show.html.erb
  app/views/bulkrax/importers/show.html.erb
  app/views/bulkrax/shared/_collection_entries_tab.html.erb
  app/views/bulkrax/shared/_file_set_entries_tab.html.erb
  app/views/bulkrax/shared/_work_entries_tab.html.erb
Labels: enhancement, patch-ver

#623 591 export from one tenant into another
  app/models/bulkrax/csv_entry.rb
  app/parsers/bulkrax/csv_parser.rb
  spec/models/bulkrax/csv_entry_spec.rb
  spec/parsers/bulkrax/bagit_parser_spec.rb
  spec/parsers/bulkrax/csv_parser_spec.rb
Labels: enhancement, minor-ver

#625 TODO-fix-csv-parser-spec
  spec/parsers/bulkrax/csv_parser_spec.rb
Labels: enhancement, ignore-for-release, samvera-labs promotion

#628 minor version bump to 4.3.0
  Gemfile.lock
  lib/bulkrax/version.rb
Labels: ignore-for-release

#629 354-use-configured-base-paths
  lib/bulkrax.rb
  spec/lib/bulkrax_spec.rb
Labels: patch-ver, bug-fix

#626 remove-reference-to-cla
  CONTRIBUTING.md
Labels: ignore-for-release, samvera-labs promotion

#634 update contributing.md while testing appending "i" to a branch name
  CONTRIBUTING.md
Labels: ignore-for-release

#630 🐛 add `required` for `Export From` fields
  app/assets/javascripts/bulkrax/exporters.js
  app/views/bulkrax/exporters/_form.html.erb
Labels: minor-ver, bug-fix

#640 pass attrs to actor stack to be used for visibility of filesets
  app/factories/bulkrax/object_factory.rb
Labels: enhancement, minor-ver, bug-fix

#642 Ensuring that we load the Bulkrax::VERSION
  lib/bulkrax.rb
Labels: ignore-for-release

#643 i-638-remote-files-import-with-FileSet
  app/factories/bulkrax/object_factory.rb
  app/models/concerns/bulkrax/file_set_entry_behavior.rb
  spec/models/bulkrax/csv_file_set_entry_spec.rb
Labels: enhancement, minor-ver

#645 I 638 remote files import with file set (part 2)
  app/factories/bulkrax/object_factory.rb
Labels: ignore-for-release, bug-fix
