Repository samvera/bulkrax, pull requests merged in 2022-11, with the labels that each got.

#663 Refactoring to remove conditional
  app/models/bulkrax/importer.rb
  app/parsers/bulkrax/application_parser.rb
Labels: enhancement, patch-ver

#664 Merge default field mapping in with field mapping
  app/models/bulkrax/importer.rb
Labels: patch-ver, bug-fix

#665 Fix misspelling in deprecation warning that was leading to a "Constant not Found" error
  app/parsers/bulkrax/csv_parser.rb
Labels: patch-ver, bug-fix

#666 Fix issue with path variable not being used
  app/views/bulkrax/shared/_file_set_entries_tab.html.erb
Labels: patch-ver, bug-fix

#668 Support customized sidebar partials if Hyrax 3.0 config is present
  app/views/hyrax/dashboard/sidebar/_bulkrax_sidebar_additions.html.erb
  app/views/hyrax/dashboard/sidebar/_repository_content.html.erb
Labels: patch-ver

#670 Convert csv headers by explicit lambda
  app/models/bulkrax/csv_entry.rb
  spec/fixtures/csv/mixed-case.csv
  spec/models/bulkrax/csv_entry_spec.rb
Labels: enhancement, minor-ver

#671 Fix `Hyrax::VisibilityPropagator` error for remote files
  app/factories/bulkrax/object_factory.rb
Labels: minor-ver, bug-fix

#675 fallback to default
  app/models/concerns/bulkrax/import_behavior.rb
Labels: minor-ver, bug-fix

#673 add configuration for using a custom ObjectFactory
  app/models/concerns/bulkrax/import_behavior.rb
  lib/bulkrax.rb
  lib/generators/bulkrax/templates/config/initializers/bulkrax.rb
Labels: minor-ver

#677 Ensuring metadata_prefix option is correctly passed
  app/controllers/bulkrax/importers_controller.rb
  app/parsers/bulkrax/oai_dc_parser.rb
Labels: patch-ver, bug-fix

#648 add reset task for hyrax to bulkrax
  lib/tasks/reset.rake
Labels: enhancement, minor-ver

#678 change the way we lookup collection ids
  app/models/bulkrax/oai_entry.rb
Labels: patch-ver
