Repository samvera/bulkrax, pull requests merged in 2022-04, with the labels that each got.

#451 update-collection-handling
  app/models/bulkrax/csv_entry.rb
  spec/jobs/bulkrax/importer_job_spec.rb
Labels: cla-signed, bug-fix

#453 remove-empty-id-when-setting-object-attrs
  app/factories/bulkrax/object_factory.rb
  spec/jobs/bulkrax/importer_job_spec.rb
Labels: enhancement, cla-signed

#457 Bulkrax 3+ update to display collection title on importer show page w…
  app/views/bulkrax/importers/show.html.erb
Labels: cla-signed, bug-fix

#458 update bulkrax to v.3.0.0.beta4
  Gemfile.lock
  lib/bulkrax/version.rb
Labels: cla-signed, ignore-for-release

#465 identifier-mixup
  app/models/bulkrax/csv_entry.rb
Labels: cla-signed, bug-fix

#467 Export generated metadata
  app/controllers/bulkrax/exporters_controller.rb
  app/models/bulkrax/csv_entry.rb
  app/models/bulkrax/exporter.rb
  app/views/bulkrax/exporters/_form.html.erb
  app/views/bulkrax/exporters/show.html.erb
  config/locales/bulkrax.en.yml
  db/migrate/20220413180915_add_generated_metadata_to_bulkrax_exporters.rb
  spec/models/bulkrax/csv_entry_spec.rb
  spec/test_app/db/schema.rb
Labels: enhancement, cla-signed

#463 streamline parents lookup per run.
  app/models/bulkrax/importer_run.rb
  app/models/concerns/bulkrax/import_behavior.rb
  db/migrate/20220301020307_add_parents_to_bulkrax_importer_runs.rb
  db/migrate/20220330165510_remove_array_true_from_importer_run_parents_column.rb
  spec/models/bulkrax/csv_entry_spec.rb
  spec/test_app/db/schema.rb
Labels: cla-signed, bug-fix

#469 semantic-collections
  app/models/bulkrax/csv_entry.rb
Labels: enhancement, cla-signed

#480 remove collection column on the importer and exporter show page
  app/views/bulkrax/exporters/show.html.erb
  app/views/bulkrax/importers/show.html.erb
Labels: enhancement, cla-signed

#484 3rd attempt to push branch for pending icon
  app/views/bulkrax/exporters/show.html.erb
  app/views/bulkrax/importers/show.html.erb
Labels: enhancement, cla-signed

#486 Generated metadata and thumbnails hint text 2
  app/views/bulkrax/exporters/_form.html.erb
  config/locales/bulkrax.en.yml
Labels: enhancement, cla-signed

#490 Rework export enhancements in prep for roundtrip
  app/models/bulkrax/csv_entry.rb
  app/models/bulkrax/entry.rb
  app/parsers/bulkrax/application_parser.rb
  app/views/bulkrax/exporters/show.html.erb
  lib/bulkrax.rb
  spec/factories/bulkrax_exporters.rb
  spec/models/bulkrax/entry_spec.rb
  spec/parsers/bulkrax/csv_parser_spec.rb
Labels: enhancement, cla-signed

#477 unable to reference a parent work/collection by id in 3.0+
  app/factories/bulkrax/object_factory.rb
  app/jobs/bulkrax/create_relationships_job.rb
  app/models/concerns/bulkrax/dynamic_record_lookup.rb
  spec/jobs/bulkrax/create_relationships_job_spec.rb
  spec/models/concerns/bulkrax/dynamic_record_lookup_spec.rb
Labels: cla-signed, bug-fix

#492 version bump to 3.0.0.beta5
  Gemfile.lock
  lib/bulkrax/version.rb
Labels: cla-signed, ignore-for-release

#493 Include v.3.0.0.beta5 updates
  Gemfile.lock
  app/factories/bulkrax/object_factory.rb
  app/jobs/bulkrax/create_relationships_job.rb
  app/models/concerns/bulkrax/dynamic_record_lookup.rb
  lib/bulkrax/version.rb
  spec/jobs/bulkrax/create_relationships_job_spec.rb
  spec/models/concerns/bulkrax/dynamic_record_lookup_spec.rb
Labels: cla-signed, ignore-for-release

#494 Random nomethoderror import
  app/models/bulkrax/csv_entry.rb
Labels: cla-signed, bug-fix

#497 Remove check for CLA from CI
  .github/workflows/release_labels.yml
Labels: ignore-for-release

#496 Use dynamic solr field for work_identifier
  app/parsers/bulkrax/csv_parser.rb
Labels: cla-signed, bug-fix

#498 Random NoMethodError on import
  app/models/bulkrax/csv_entry.rb
Labels: cla-signed, bug-fix

#499 Better error message for FileSets missing files
  app/models/bulkrax/csv_entry.rb
  app/models/bulkrax/csv_file_set_entry.rb
  spec/models/bulkrax/csv_file_set_entry_spec.rb
Labels: enhancement

#500 sixth beta release for v3.0.0
  Gemfile.lock
  lib/bulkrax/version.rb
Labels: ignore-for-release
