Repository samvera/bulkrax, pull requests merged in 2022-05, with the labels that each got.

#507 remove ruby 2.5 from testing as 2.5 is EOL
  .github/workflows/test.yml
  spec/jobs/bulkrax/importer_job_spec.rb
Labels: breaking-change

#508 Remove legacy collection relationships logic from object factory
  app/factories/bulkrax/object_factory.rb
  app/jobs/bulkrax/create_relationships_job.rb
  spec/jobs/bulkrax/create_relationships_job_spec.rb
Labels: bug-fix

#510 update Bulkrax to v3.0.0.beta7
  Gemfile.lock
  lib/bulkrax/version.rb
Labels: ignore-for-release

#512 eighth beta release for v3.0.0
  Gemfile.lock
  lib/bulkrax/version.rb
Labels: ignore-for-release

#514 Bump to version 3.0
  Gemfile.lock
  lib/bulkrax/version.rb
Labels: ignore-for-release

#517 Erroneous complete status
  app/jobs/bulkrax/export_work_job.rb
  app/models/bulkrax/exporter.rb
  app/parsers/bulkrax/csv_parser.rb
  spec/models/bulkrax/exporter_spec.rb
  spec/parsers/bulkrax/csv_parser_spec.rb
Labels: bug-fix

#518 Erroneous complete status
  app/jobs/bulkrax/export_work_job.rb
  app/models/bulkrax/exporter.rb
  app/parsers/bulkrax/csv_parser.rb
  spec/models/bulkrax/exporter_spec.rb
  spec/parsers/bulkrax/csv_parser_spec.rb
Labels: bug-fix

#519 Fix Collection-to-Work relationship assigning
  app/jobs/bulkrax/create_relationships_job.rb
  app/models/bulkrax/importer.rb
  app/models/concerns/bulkrax/import_behavior.rb
  spec/jobs/bulkrax/create_relationships_job_spec.rb
Labels: bug-fix

#515 Account for commons mistakes when importing controlled Questioning Authority fields
  app/models/bulkrax/csv_entry.rb
  app/models/concerns/bulkrax/import_behavior.rb
  lib/bulkrax.rb
  lib/generators/bulkrax/templates/config/initializers/bulkrax.rb
  spec/models/bulkrax/csv_entry_spec.rb
  spec/test_app/app/models/work.rb
  spec/test_app/config/authorities/rights_statements.yml
Labels: enhancement

#523 minor version bump v3.1.0
  Gemfile.lock
  lib/bulkrax/version.rb
Labels: ignore-for-release

#525 Small README updates
  README.md
Labels: ignore-for-release

#526 Fix exports from importers including unrelated records
  app/parsers/bulkrax/csv_parser.rb
Labels: bug-fix

#528 update pals branch with the latest code from main
  Gemfile.lock
  README.md
  app/jobs/bulkrax/create_relationships_job.rb
  app/models/bulkrax/csv_entry.rb
  app/models/bulkrax/importer.rb
  app/models/concerns/bulkrax/import_behavior.rb
  app/parsers/bulkrax/csv_parser.rb
  lib/bulkrax.rb
  lib/bulkrax/version.rb
  lib/generators/bulkrax/templates/config/initializers/bulkrax.rb
  spec/jobs/bulkrax/create_relationships_job_spec.rb
  spec/models/bulkrax/csv_entry_spec.rb
  spec/test_app/app/models/work.rb
  spec/test_app/config/authorities/rights_statements.yml
Labels: ignore-for-release

#527 patch version bump v3.1.1
  Gemfile.lock
  lib/bulkrax/version.rb
Labels: ignore-for-release

#531 better entry lookup
  app/models/concerns/bulkrax/dynamic_record_lookup.rb
  spec/jobs/bulkrax/create_relationships_job_spec.rb
  spec/models/concerns/bulkrax/dynamic_record_lookup_spec.rb
Labels: bug-fix

#532 erroneous pending status on import
  app/jobs/bulkrax/create_relationships_job.rb
Labels: bug-fix

#535 collection_created rework
  app/models/bulkrax/csv_entry.rb
Labels: enhancement

#529 Use #key_for_export instead of always exporting model as "model"
  app/models/bulkrax/csv_entry.rb
  spec/models/bulkrax/csv_entry_spec.rb
Labels: enhancement

#536 Cache CsvParser#records method
  app/parsers/bulkrax/csv_parser.rb
Labels: bug-fix

#540 minor version bump v3.2.0
  Gemfile.lock
  lib/bulkrax/version.rb
Labels: ignore-for-release
