Repository samvera/bulkrax, pull requests merged in 2022-10, with the labels that each got.

#657 downgrade-migration-versions-to-five-point-one
  db/migrate/20211203195233_rename_children_counters_to_relationships.rb
  db/migrate/20211220195027_add_file_set_counters_to_importer_runs.rb
  db/migrate/20220118001339_add_import_attempts_to_entries.rb
  db/migrate/20220119213325_add_work_counters_to_importer_runs.rb
  db/migrate/20220301001839_create_bulkrax_pending_relationships.rb
  db/migrate/20220303212810_add_order_to_bulkrax_pending_relationships.rb
  db/migrate/20220412233954_add_include_thumbnails_to_bulkrax_exporters.rb
  db/migrate/20220413180915_add_generated_metadata_to_bulkrax_exporters.rb
  db/migrate/20220609001128_rename_bulkrax_importer_run_to_importer_run.rb
  spec/test_app/db/migrate/20220726162605_create_site.rb
  spec/test_app/db/migrate/20220726164334_create_account.rb
Labels: dependencies, minor-ver, database-changes

#659 Adding inline documentation
  app/parsers/bulkrax/application_parser.rb
Labels: ignore-for-release

#662 Adding Bulkrax::RemoveRelationshipsForImporter
  app/services/bulkrax/remove_relationships_for_importer.rb
  spec/services/bulkrax/remove_relationships_for_importer_spec.rb
Labels: enhancement, ignore-for-release
