Repository samvera/bulkrax, pull requests merged in 2023-06, with the labels that each got.

#814 📚 Add / correct documentation
  README.md
  lib/generators/bulkrax/templates/config/initializers/bulkrax.rb
Labels: patch-ver

#813 🎁 Adding indices to Bulkrax Tables
  .github/workflows/test.yml
  bulkrax.gemspec
  db/migrate/20230608153601_add_indices_to_bulkrax.rb
  spec/test_app/config/database.yml
  spec/test_app/config/initializers/redis_config.rb
  spec/test_app/db/schema.rb
Labels: patch-ver

#815 :lipstick: fix cause of NoMethodError due to typo
  app/parsers/bulkrax/parser_export_record_set.rb
Labels: ignore-for-release

#816 :gift: remove whitespaces from CSV headers
  app/models/bulkrax/csv_entry.rb
Labels: patch-ver

#821 Fix create and validate button
  app/views/bulkrax/importers/new.html.erb
Labels: bug, patch-ver

#822 🐛 Move "|" button separator to be within conditional
  app/views/bulkrax/importers/new.html.erb
Labels: ignore-for-release
