Repository samvera/bulkrax, pull requests merged in 2023-05, with the labels that each got.

#802 strip whitespace from model values so they get assigned correctly
  app/parsers/bulkrax/csv_parser.rb
  spec/fixtures/csv/all_record_types_whitespace.csv
  spec/parsers/bulkrax/csv_parser_spec.rb
Labels: patch-ver

#773 Default ordering importers/exporters by created_at: :desc
  app/controllers/bulkrax/exporters_controller.rb
  app/controllers/bulkrax/importers_controller.rb
Labels: patch-ver

#807 ⚙️ Adding Solargraph to Gemfile for lovely LSP improvements
  Gemfile
Labels: ignore-for-release

#808 ♻️ Adding Bulkrax::ParserExportRecordSet.in_batches
  app/parsers/bulkrax/parser_export_record_set.rb
  spec/parsers/bulkrax/parser_export_record_set_spec.rb
Labels: ignore-for-release

#809 🐛 Adding in_batches handling of Importer based export
  app/parsers/bulkrax/parser_export_record_set.rb
Labels: patch-ver, bug-fix

#812 🐛 Reindex child work after adding relationship
  app/jobs/bulkrax/create_relationships_job.rb
  spec/jobs/bulkrax/create_relationships_job_spec.rb
Labels: patch-ver, bug-fix

#811 🐛 Add record locking for create_relationships_job
  app/jobs/bulkrax/create_relationships_job.rb
  lib/bulkrax.rb
Labels: patch-ver, bug-fix
