Repository samvera/bulkrax, pull requests merged in 2023-04, with the labels that each got.

#778 HotFix: Patching Marcel MimeType sniffing
  app/models/concerns/bulkrax/importer_exporter_behavior.rb
  app/parsers/bulkrax/application_parser.rb
Labels: patch-ver, bug-fix

#779 Adding spec to verify zip? detection
  app/parsers/bulkrax/application_parser.rb
  spec/fixtures/zip/simple.zip
  spec/models/bulkrax/importer_spec.rb
  spec/parsers/bulkrax/application_parser_spec.rb
Labels: patch-ver, bug-fix

#780 Ensuring closed file handle when testing zip file
  app/models/concerns/bulkrax/importer_exporter_behavior.rb
Labels: patch-ver

#781 move config to a Configurable class
  lib/bulkrax.rb
Labels: enhancement, minor-ver

#784 filters out arrays with empty strings
  app/factories/bulkrax/object_factory.rb
Labels: patch-ver

#785 patch version bump 4.3.1
  Gemfile.lock
  lib/bulkrax/version.rb
Labels: ignore-for-release

#786 Add more labels for view pages
  app/views/bulkrax/exporters/show.html.erb
  app/views/bulkrax/importers/show.html.erb
  app/views/bulkrax/shared/_collection_entries_tab.html.erb
  app/views/bulkrax/shared/_file_set_entries_tab.html.erb
  app/views/bulkrax/shared/_work_entries_tab.html.erb
  config/locales/bulkrax.en.yml
Labels: minor-ver

#788 patch version bump 4.4.1
  Gemfile.lock
  lib/bulkrax/version.rb
Labels: ignore-for-release

#783 Non hyrax exports
  app/jobs/bulkrax/schedule_relationships_job.rb
  app/models/bulkrax/csv_entry.rb
  app/parsers/bulkrax/parser_export_record_set.rb
  app/views/bulkrax/entries/show.html.erb
  app/views/bulkrax/exporters/_form.html.erb
  lib/bulkrax.rb
  spec/lib/bulkrax_spec.rb
Labels: patch-ver

#789 Update bulkrax.rb rel job var
  lib/bulkrax.rb
Labels: patch-ver, bug-fix

#790 Fix multi_value_element_split_on example regex
  lib/generators/bulkrax/templates/config/initializers/bulkrax.rb
Labels: patch-ver

#792 minor-version-bump-v5.2.0
  lib/bulkrax/version.rb
Labels: ignore-for-release

#793 default-fs-entry-class
  app/parsers/bulkrax/oai_dc_parser.rb
Labels: patch-ver

#797 v 4.4.2
  lib/bulkrax/version.rb
Labels: ignore-for-release

#798 fix bagit exporting
  app/parsers/bulkrax/bagit_parser.rb
Labels: patch-ver

#799 upgrade to v5.2.1
  lib/bulkrax/version.rb
Labels: ignore-for-release

#800 add #create_relationships to ::OaiDcParser
  app/parsers/bulkrax/oai_dc_parser.rb
Labels: patch-ver
