Repository samvera/bulkrax, pull requests merged in 2023-08, with the labels that each got.

#839 Prefer [] over [""] for blank values that are split
  app/matchers/bulkrax/application_matcher.rb
  app/models/bulkrax/importer.rb
Labels: minor-ver, bug-fix

#847 🐛 Normalizing export column names
  app/models/bulkrax/csv_entry.rb
  spec/models/bulkrax/csv_entry_spec.rb
Labels: patch-ver, bug-fix

#848 💸 Minting version 5.3.0
  lib/bulkrax/version.rb
Labels: ignore-for-release

#852 small pr to make all migrations skipable and updated last one to match existing pattern
  db/migrate/20210806044408_remove_unused_last_error.rb
  db/migrate/20230608153601_add_indices_to_bulkrax.rb
Labels: ignore-for-release

#855 🐛 Ensuring we inject Bulkrax views before Hyrax
  lib/bulkrax/engine.rb
Labels: patch-ver, bug-fix
