Repository samvera/bulkrax, pull requests merged in 2023-01, with the labels that each got.

#703 Ensuring OAI parser sets factory class then parses
  app/models/bulkrax/oai_entry.rb
  spec/models/bulkrax/oai_entry_spec.rb
Labels: patch-ver, bug-fix

#705 Ensuring XML parser sets factory class then parses
  app/models/bulkrax/xml_entry.rb
  spec/models/bulkrax/xml_entry_spec.rb
Labels: patch-ver, bug-fix

#706 Remove errored tab
  app/controllers/bulkrax/importers_controller.rb
  app/views/bulkrax/importers/show.html.erb
  app/views/bulkrax/shared/_errored_entries_tab.html.erb
Labels: patch-ver, bug-fix

#708 Scour blank strings from the creation attributes
  app/factories/bulkrax/object_factory.rb
  lib/bulkrax.rb
  spec/factories/bulkrax/object_factory_spec.rb
Labels: patch-ver, bug-fix

#710 Adding ApplicationParser#file_set_entry_class to API
  app/parsers/bulkrax/application_parser.rb
  app/parsers/bulkrax/xml_parser.rb
Labels: patch-ver

#700 Replace solrizer reference so that feature works with hyrax 3+
  app/parsers/bulkrax/csv_parser.rb
Labels: patch-ver

#707 Add Permissions For Bulkrax
  Gemfile
  Gemfile.lock
  app/controllers/bulkrax/entries_controller.rb
  app/controllers/bulkrax/exporters_controller.rb
  app/controllers/bulkrax/importers_controller.rb
  app/views/hyrax/dashboard/sidebar/_bulkrax_sidebar_additions.html.erb
  app/views/hyrax/dashboard/sidebar/_repository_content.html.erb
  lib/generators/bulkrax/install_generator.rb
  spec/controllers/bulkrax/exporters_controller_spec.rb
  spec/controllers/bulkrax/importers_controller_spec.rb
  spec/jobs/bulkrax/create_relationships_job_spec.rb
  spec/jobs/bulkrax/import_file_set_job_spec.rb
  spec/models/bulkrax/csv_file_set_entry_spec.rb
  spec/models/bulkrax/object_factory_spec.rb
  spec/rails_helper.rb
  spec/support/dynamic_record_lookup.rb
  spec/test_app/app/controllers/application_controller.rb
  spec/test_app/app/models/ability.rb
  spec/test_app/app/models/user.rb
  spec/test_app/config/application.rb
Labels: major-ver, bug-fix

#713 Fixing bug introduced in #663
  app/parsers/bulkrax/application_parser.rb
  spec/parsers/bulkrax/application_parser_spec.rb
Labels: patch-ver, bug-fix

#712 Convert source_identifier from relationship to single value
  app/models/bulkrax/csv_entry.rb
  spec/models/bulkrax/csv_entry_spec.rb
Labels: patch-ver, bug-fix

#696 Allow single value fields with controlled vocabs
  app/models/concerns/bulkrax/import_behavior.rb
  spec/models/bulkrax/csv_entry_spec.rb
Labels: patch-ver, bug-fix

#715 update libxml-ruby
  bulkrax.gemspec
Labels: dependencies, patch-ver

#719 Ensuring CSV sets factory class before metadata parsing
  app/models/bulkrax/csv_entry.rb
  spec/fixtures/csv/factory_class_test.csv
  spec/models/bulkrax/csv_entry_spec.rb
Labels: patch-ver, bug-fix

#687 Favoring class_attribute over inline array
  app/matchers/bulkrax/application_matcher.rb
Labels: minor-ver

#720 major version bump to 5.0.0
  lib/bulkrax/version.rb
Labels: ignore-for-release

#722 Adding config to reindex child work's file sets
  app/jobs/bulkrax/create_relationships_job.rb
  spec/jobs/bulkrax/create_relationships_job_spec.rb
Labels: enhancement, patch-ver
