Repository samvera/bulkrax, pull requests merged in 2023-03, with the labels that each got.

#753 filters out keys with blank values for required elements check
  app/models/bulkrax/csv_entry.rb
  app/parsers/bulkrax/csv_parser.rb
  spec/factories/bulkrax_entries.rb
  spec/parsers/bulkrax/csv_parser_spec.rb
Labels: patch-ver, bug-fix

#759 Ensuring exporter's queried file sets are in fact file sets
  app/parsers/bulkrax/parser_export_record_set.rb
  spec/parsers/bulkrax/parser_export_record_set_spec.rb
Labels: patch-ver, bug-fix

#763 Update reset.rake
  lib/tasks/reset.rake
Labels: patch-ver, bug-fix

#744 decouple from hyrax
  app/controllers/bulkrax/importers_controller.rb
  app/jobs/bulkrax/create_relationships_job.rb
  app/jobs/bulkrax/importer_job.rb
  app/jobs/bulkrax/schedule_relationships_job.rb
  app/matchers/bulkrax/application_matcher.rb
  app/models/bulkrax/csv_entry.rb
  app/models/bulkrax/exporter.rb
  app/models/concerns/bulkrax/dynamic_record_lookup.rb
  app/models/concerns/bulkrax/export_behavior.rb
  app/models/concerns/bulkrax/import_behavior.rb
  app/models/concerns/bulkrax/importer_exporter_behavior.rb
  app/parsers/bulkrax/application_parser.rb
  app/parsers/bulkrax/bagit_parser.rb
  app/parsers/bulkrax/oai_dc_parser.rb
  app/parsers/bulkrax/parser_export_record_set.rb
  app/parsers/bulkrax/xml_parser.rb
  app/services/bulkrax/remove_relationships_for_importer.rb
  app/views/bulkrax/exporters/_form.html.erb
  app/views/bulkrax/importers/_bagit_fields.html.erb
  app/views/bulkrax/importers/_csv_fields.html.erb
  app/views/bulkrax/importers/_oai_fields.html.erb
  app/views/bulkrax/importers/_xml_fields.html.erb
  lib/bulkrax.rb
  spec/fixtures/xml/good.xml
Labels: enhancement, minor-ver

#765 745 use correct mapping for required fields
  app/parsers/bulkrax/application_parser.rb
  app/parsers/bulkrax/csv_parser.rb
  lib/bulkrax.rb
Labels: bug, patch-ver

#764 Improve CreateRelationshipsJob's performance by setting reindexing to LIMITED_REINDEX
  app/jobs/bulkrax/create_relationships_job.rb
Labels: ignore-for-release

#757 add rights_statement to list of fields with multiple values
  app/models/concerns/bulkrax/has_matchers.rb
Labels: patch-ver, bug-fix

#766 Admin set decouple
  app/helpers/bulkrax/validation_helper.rb
  app/models/bulkrax/csv_entry.rb
  app/models/concerns/bulkrax/import_behavior.rb
  app/views/bulkrax/importers/show.html.erb
Labels: enhancement, patch-ver

#769 Fixing timing regression for incrementation
  app/jobs/bulkrax/import_work_job.rb
Labels: patch-ver, bug-fix

#770 Adding guard for querying 0 rows for FileSets
  app/parsers/bulkrax/parser_export_record_set.rb
Labels: patch-ver, bug-fix

#768 Deprecate parse_resource_type method as it isn't used anymore
  app/matchers/bulkrax/application_matcher.rb
Labels: patch-ver

#776 Addressing SOLR maxBooleanClauses for WorkType export
  app/parsers/bulkrax/parser_export_record_set.rb
Labels: patch-ver, bug-fix
