Repository samvera/bulkrax, pull requests merged in 2023-10, with the labels that each got.

#862 :bug: add guard clauses to add_indices_to_bulkrax migration
  db/migrate/20230608153601_add_indices_to_bulkrax.rb
Labels: minor-ver

#864 💸 Minor bump to v5.4.0
  lib/bulkrax/version.rb
Labels: ignore-for-release

#865 5.4.0-bug-fixes
  app/factories/bulkrax/object_factory.rb
  app/views/bulkrax/importers/_oai_fields.html.erb
Labels: patch-ver

#870 Avoid NoMethodError in Bulkrax::Importers::Controller#create.
  app/parsers/bulkrax/csv_parser.rb
Labels: patch-ver, bug-fix

#873 📚 Update docs in preparation for best practices seminar
  lib/bulkrax/entry_spec_helper.rb
Labels: patch-ver

#874 Nav-tabs event scoping
  app/assets/javascripts/bulkrax/navtabs.js.erb
Labels: patch-ver, bug-fix

#875 🐛 Fix tabs for Hydra application
  app/assets/javascripts/bulkrax/navtabs.js.erb
  app/views/bulkrax/shared/_bulkrax_errors.html.erb
Labels: patch-ver

#879 add Compatibility section to readme
  README.md
Labels: patch-ver, samvera-labs promotion

#881 Reduce SQL calls when incrementing/decrementing run counters
  app/jobs/bulkrax/create_relationships_job.rb
  app/jobs/bulkrax/delete_job.rb
  app/jobs/bulkrax/export_work_job.rb
  app/jobs/bulkrax/import_collection_job.rb
  app/jobs/bulkrax/import_file_set_job.rb
  app/jobs/bulkrax/import_work_job.rb
  app/parsers/bulkrax/application_parser.rb
  spec/factories/bulkrax_exporter_runs.rb
  spec/factories/bulkrax_importer_runs.rb
  spec/jobs/bulkrax/delete_work_job_spec.rb
  spec/jobs/bulkrax/export_work_job_spec.rb
  spec/jobs/bulkrax/import_file_set_job_spec.rb
  spec/jobs/bulkrax/import_work_job_spec.rb
  spec/test_app/db/schema.rb
Labels: patch-ver
