Repository samvera/bulkrax, pull requests merged in 2023-11, with the labels that each got.

#883 fix syntax error in ERB
  app/views/hyrax/dashboard/sidebar/_bulkrax_sidebar_additions.html.erb
Labels: patch-ver, bug-fix

#885 unpin dry-monads. its not a dependency of bulkrax
  bulkrax.gemspec
Labels: patch-ver

#888 💸 v5.5.0
  lib/bulkrax/version.rb
Labels: minor-ver

#884 make search string used to look up objects configurable
  .rubocop.yml
  Gemfile
  app/controllers/bulkrax/importers_controller.rb
  app/factories/bulkrax/object_factory.rb
  app/models/concerns/bulkrax/import_behavior.rb
  app/parsers/bulkrax/application_parser.rb
  lib/generators/bulkrax/templates/config/initializers/bulkrax.rb
  lib/tasks/bulkrax_tasks.rake
  spec/factories/bulkrax/object_factory_spec.rb
  spec/factories/bulkrax_object_factories.rb
  spec/models/bulkrax/object_factory_spec.rb
  spec/rails_helper.rb
Labels: enhancement, major-ver, breaking-change

#889 💸 Bump to v6.0.0
  lib/bulkrax/version.rb
Labels: ignore-for-release
