Repository samvera/bulkrax, pull requests merged in 2023-02, with the labels that each got.

#725 Ensuring self-contained memoization of method
  app/models/bulkrax/oai_entry.rb
  spec/models/bulkrax/oai_entry_spec.rb
Labels: bug, patch-ver

#728 check if Hyrax is defined
  app/controllers/bulkrax/entries_controller.rb
  app/controllers/bulkrax/exporters_controller.rb
  app/controllers/bulkrax/importers_controller.rb
  app/helpers/bulkrax/application_helper.rb
Labels: bug, patch-ver, bug-fix

#736 add bootstrap classes to forms
  app/views/bulkrax/exporters/_form.html.erb
  app/views/bulkrax/exporters/edit.html.erb
  app/views/bulkrax/exporters/new.html.erb
  app/views/bulkrax/importers/_form.html.erb
Labels: patch-ver, bug-fix

#738 Renaming method to reflect it's state changing nature
  app/jobs/bulkrax/create_relationships_job.rb
  app/jobs/bulkrax/delete_job.rb
  app/jobs/bulkrax/export_work_job.rb
  app/jobs/bulkrax/import_file_set_job.rb
  app/jobs/bulkrax/importer_job.rb
  app/models/bulkrax/importer.rb
  app/models/concerns/bulkrax/status_info.rb
  app/parsers/bulkrax/bagit_parser.rb
  spec/jobs/bulkrax/import_file_set_job_spec.rb
Labels: enhancement, minor-ver

#739 only uses admin sets if Hyrax is present
  app/helpers/bulkrax/importers_helper.rb
  app/models/bulkrax/importer.rb
  app/views/bulkrax/importers/_form.html.erb
Labels: patch-ver

#737 replace multiple times through the pending realtionship loop
  app/jobs/bulkrax/create_relationships_job.rb
  app/models/bulkrax/importer_run.rb
  app/models/bulkrax/pending_relationship.rb
  app/models/concerns/bulkrax/dynamic_record_lookup.rb
  lib/bulkrax.rb
  spec/factories/bulkrax/pending_relationships.rb
  spec/jobs/bulkrax/create_relationships_job_spec.rb
  spec/models/bulkrax/importer_run_spec.rb
Labels: minor-ver, bug-fix

#740 Fix #add_to_work
  app/jobs/bulkrax/create_relationships_job.rb
Labels: patch-ver, bug-fix

#741 Capturing record and header metadata for OAI parser
  app/models/bulkrax/oai_entry.rb
Labels: patch-ver

#742 Expanding `Bulkrax::EntrySpecHelper` to handle collections
  lib/bulkrax/entry_spec_helper.rb
Labels: enhancement, patch-ver

#734 exporter errors for non hyrax apps
  app/models/bulkrax/exporter.rb
  app/views/bulkrax/exporters/_form.html.erb
Labels: bug, patch-ver, bug-fix

#743 instrament realtionship job to solve memory leak
  app/jobs/bulkrax/create_relationships_job.rb
Labels: patch-ver, bug-fix

#748 minor version bump to 5.1.0
  lib/bulkrax/version.rb
Labels: ignore-for-release

#746 Favoring non-deprecated method name
  app/models/bulkrax/exporter.rb
  app/models/bulkrax/importer.rb
  app/models/bulkrax/pending_relationship.rb
  app/models/concerns/bulkrax/export_behavior.rb
  app/models/concerns/bulkrax/import_behavior.rb
  app/parsers/bulkrax/application_parser.rb
  app/parsers/bulkrax/bagit_parser.rb
  app/parsers/bulkrax/csv_parser.rb
  app/parsers/bulkrax/xml_parser.rb
Labels: patch-ver

#749 Adding `Bulkrax::ParserExportRecordSet`
  app/parsers/bulkrax/bagit_parser.rb
  app/parsers/bulkrax/csv_parser.rb
  app/parsers/bulkrax/parser_export_record_set.rb
  lib/bulkrax/entry_spec_helper.rb
  spec/features/bagit_exporter_spec.rb
  spec/parsers/bulkrax/bagit_parser_spec.rb
  spec/parsers/bulkrax/csv_parser_spec.rb
  spec/parsers/bulkrax/parser_export_record_set_spec.rb
Labels: enhancement, patch-ver, bug-fix

#750 remove space before method call
  app/parsers/bulkrax/csv_parser.rb
Labels: ignore-for-release

#747 i289 Exporter Issue
  app/models/bulkrax/csv_entry.rb
  app/models/bulkrax/exporter.rb
  spec/models/bulkrax/csv_entry_spec.rb
Labels: enhancement, patch-ver, bug-fix

#752 Favoring explicit "empty" lines handler
  app/models/bulkrax/csv_entry.rb
  spec/fixtures/csv/entry-causing-problems-in-2.7.6.csv
  spec/models/bulkrax/csv_entry_spec.rb
Labels: patch-ver, bug-fix
