Repository samvera/bulkrax, pull requests merged in 2023-07, with the labels that each got.

#835 Fix modal for hydra apps
  app/views/bulkrax/importers/edit.html.erb
Labels: patch-ver, bug-fix

#836 Re-enables nav-tabs for hydra apps
  Gemfile
  app/assets/javascripts/bulkrax/application.js
  app/assets/javascripts/bulkrax/navtabs.js
Labels: patch-ver

#838 🎁 Add title attribute
  app/views/hyrax/dashboard/sidebar/_bulkrax_sidebar_additions.html.erb
  app/views/hyrax/dashboard/sidebar/_repository_content.html.erb
Labels: minor-ver

#841 Remove jquery and bootstrap from bulkrax
  app/assets/javascripts/bulkrax/application.js
Labels: patch-ver

#843 🐛 Modify navtabs.js
  app/assets/javascripts/bulkrax/navtabs.js
  app/assets/javascripts/bulkrax/navtabs.js.erb
Labels: patch-ver
