Repository samvera/bulkrax, pull requests merged in 2024-09, with the labels that each got.

#976 Importing local files broke due to remote files work
  app/factories/bulkrax/valkyrie_object_factory.rb
Labels: ignore-for-release, bug-fix

#977 🐛 Fix importers sorting for last run and next run
  .github/workflows/test.yml
  app/assets/javascripts/bulkrax/datatables.js
  app/models/bulkrax/importer.rb
  app/models/bulkrax/importer_run.rb
  db/migrate/20240916182737_add_last_imported_at_to_bulkrax_importers.rb
  db/migrate/20240916182823_add_next_import_at_to_bulkrax_importers.rb
  lib/tasks/bulkrax_tasks.rake
Labels: patch-ver, bug-fix

#979 Add import_url to file set attributes
  app/factories/bulkrax/valkyrie_object_factory.rb
Labels: patch-ver

#980 Avoid false positive from `.try(:internal_resource)`
  lib/bulkrax.rb
Labels: patch-ver
