Repository samvera/bulkrax, pull requests merged in 2024-02, with the labels that each got.

#907 use find_by_source_identifier instead of find_by_bulkrax_identifier
  app/factories/bulkrax/valkyrie_object_factory.rb
  app/parsers/bulkrax/application_parser.rb
  app/services/hyrax/custom_queries/find_by_source_identifier.rb
  app/services/wings/custom_queries/find_by_source_identifier.rb
Labels: patch-ver

#908 🧹 Make CreateRelationshipJob work for Valkyrie
  app/factories/bulkrax/object_factory.rb
  app/jobs/bulkrax/create_relationships_job.rb
  lib/bulkrax/persistence_layer/active_fedora_adapter.rb
Labels: patch-ver

#859 importer failure helpers
  app/models/bulkrax/importer.rb
Labels: patch-ver

#910 ⚙️ Adding dry-monads as development dependency
  bulkrax.gemspec
Labels: ignore-for-release

#911 ♻️ Migrate persistence layer methods to object factory
  app/factories/bulkrax/object_factory.rb
  app/factories/bulkrax/object_factory_interface.rb
  app/factories/bulkrax/valkyrie_object_factory.rb
  app/helpers/bulkrax/validation_helper.rb
  app/jobs/bulkrax/create_relationships_job.rb
  app/models/concerns/bulkrax/dynamic_record_lookup.rb
  app/models/concerns/bulkrax/export_behavior.rb
  app/parsers/bulkrax/bagit_parser.rb
  app/parsers/bulkrax/csv_parser.rb
  app/parsers/bulkrax/parser_export_record_set.rb
  lib/bulkrax.rb
  lib/bulkrax/engine.rb
  lib/bulkrax/persistence_layer/active_fedora_adapter.rb
  lib/bulkrax/persistence_layer/valkyrie_adapter.rb
  spec/bulkrax_spec.rb
  spec/parsers/bulkrax/bagit_parser_spec.rb
  spec/parsers/bulkrax/csv_parser_spec.rb
  spec/support/dynamic_record_lookup.rb
Labels: patch-ver

#913 Denormalize Status Message to that Entry Look Up Can Be Fast
  app/models/bulkrax/importer.rb
  app/models/bulkrax/status.rb
  app/models/concerns/bulkrax/status_info.rb
  bulkrax.gemspec
  db/migrate/20240208005801_denormalize_status_message.rb
  lib/bulkrax.rb
  lib/tasks/bulkrax_tasks.rake
Labels: major-ver, breaking-change

#912 🧹 Make DeleteJob work wth new class method .find
  app/factories/bulkrax/object_factory.rb
  app/factories/bulkrax/valkyrie_object_factory.rb
  app/jobs/bulkrax/delete_job.rb
  app/parsers/bulkrax/application_parser.rb
  spec/jobs/bulkrax/delete_work_job_spec.rb
Labels: patch-ver

#917 Need to Include dry/monads in sample app to get generators working
  spec/test_app/config/application.rb
Labels: ignore-for-release

#918 Strip out all special characters from csv headers
  app/models/bulkrax/csv_entry.rb
Labels: patch-ver, bug-fix

#919 Restore rails5 support
  app/models/bulkrax/status.rb
Labels: ignore-for-release

#914 Update Importer Index and Show Entries With Search, Filtering, Sort and More
  app/assets/javascripts/bulkrax/datatables.js
  app/controllers/bulkrax/importers_controller.rb
  app/controllers/concerns/bulkrax/datatables_behavior.rb
  app/views/bulkrax/importers/index.html.erb
  app/views/bulkrax/importers/show.html.erb
  app/views/bulkrax/shared/_entries_tab.html.erb
  config/routes.rb
  spec/controllers/bulkrax/importers_controller_spec.rb
  spec/controllers/concerns/bulkrax/datatables_behavior_spec.rb
  spec/test_app/db/schema.rb
Labels: minor-ver

#920 Add Skip to the datatabels
  app/assets/javascripts/bulkrax/datatables.js
  app/controllers/concerns/bulkrax/datatables_behavior.rb
Labels: ignore-for-release

#921 For every importer / record combo there should be exactly one entry
  app/parsers/bulkrax/application_parser.rb
  db/migrate/20240209070952_update_identifier_index.rb
  spec/test_app/db/schema.rb
Labels: major-ver

#922 Mark records as skipped if we do not see them during an import run
  app/models/bulkrax/importer.rb
  app/models/concerns/bulkrax/status_info.rb
Labels: minor-ver

#923 Redo records with the remove_and_rerun property in the data, move individual remove and rerun to a background job
  .github/workflows/test.yml
  Rakefile
  app/assets/javascripts/bulkrax/importers.js.erb
  app/assets/stylesheets/bulkrax/import_export.scss
  app/controllers/bulkrax/entries_controller.rb
  app/controllers/bulkrax/importers_controller.rb
  app/jobs/bulkrax/delete_and_import_collection_job.rb
  app/jobs/bulkrax/delete_and_import_file_set_job.rb
  app/jobs/bulkrax/delete_and_import_job.rb
  app/jobs/bulkrax/delete_and_import_work_job.rb
  app/jobs/bulkrax/delete_job.rb
  app/jobs/bulkrax/import_job.rb
  app/models/bulkrax/exporter.rb
  app/models/bulkrax/importer.rb
  app/parsers/bulkrax/application_parser.rb
  app/parsers/bulkrax/bagit_parser.rb
  app/parsers/bulkrax/csv_parser.rb
  app/parsers/bulkrax/oai_dc_parser.rb
  app/parsers/bulkrax/xml_parser.rb
  app/views/bulkrax/importers/_csv_fields.html.erb
  lib/bulkrax.rb
  spec/parsers/bulkrax/application_parser_spec.rb
Labels: minor-ver

#926 Fix exporters show page - 2
  app/assets/javascripts/bulkrax/datatables.js
  app/controllers/bulkrax/exporters_controller.rb
  app/controllers/concerns/bulkrax/datatables_behavior.rb
  app/views/bulkrax/exporters/index.html.erb
  app/views/bulkrax/exporters/show.html.erb
  app/views/bulkrax/importers/show.html.erb
  app/views/bulkrax/shared/_entries_tab.html.erb
  config/routes.rb
Labels: patch-ver

#927 ♻️ Favor configuration over hard-coding
  app/jobs/bulkrax/create_relationships_job.rb
  app/jobs/bulkrax/delete_job.rb
  app/jobs/bulkrax/download_cloud_file_job.rb
  app/jobs/bulkrax/import_collection_job.rb
  app/jobs/bulkrax/import_file_set_job.rb
  app/jobs/bulkrax/import_work_job.rb
  app/jobs/bulkrax/importer_job.rb
  lib/bulkrax.rb
Labels: patch-ver

#928 🐛 Fix exporter page for Bootstrap 3 applications
  app/assets/javascripts/bulkrax/exporters.js
  app/controllers/concerns/bulkrax/datatables_behavior.rb
  app/views/bulkrax/exporters/_form.html.erb
Labels: patch-ver

#929 ♻️ Favor member_ids_ssim over file_set_ids_ssim
  app/parsers/bulkrax/parser_export_record_set.rb
  lib/bulkrax.rb
  spec/parsers/bulkrax/parser_export_record_set_spec.rb
Labels: minor-ver
