Repository samvera/bulkrax, pull requests merged in 2024-12, with the labels that each got.

#986 ActiveFedora based deletion issues
  .github/workflows/test.yml
  app/factories/bulkrax/object_factory.rb
  app/jobs/bulkrax/delete_file_set_job.rb
  spec/test_app/db/schema.rb
Labels: patch-ver

#987 prep v8.3.0 release
  lib/bulkrax/version.rb
Labels: ignore-for-release

#988 speed up entries display by no longer looking at all the status objects
  app/controllers/concerns/bulkrax/datatables_behavior.rb
  app/models/bulkrax/status.rb
  db/migrate/20241203010707_entry_error_denormalization.rb
  db/migrate/20241205212513_faster_first_entry.rb
  lib/tasks/bulkrax_tasks.rake
  spec/test_app/db/schema.rb
Labels: major-ver

#992 fix ActiveFedora delete
  app/factories/bulkrax/object_factory.rb
Labels: patch-ver

#991 Fixes issues with filesets exporting in Valkyrie
  app/models/concerns/bulkrax/export_behavior.rb
  app/parsers/bulkrax/csv_parser.rb
  app/parsers/bulkrax/parser_export_record_set.rb
Labels: patch-ver

#993 ⬆️ Up Bagit dependency to 0.6.0
  bulkrax.gemspec
Labels: patch-ver

#998 Fixes for CI Jobs
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: ignore-for-release

#994 Add guard to uploaded_files migration
  db/migrate/20240806161142_add_file_name_to_uploaded_files.rb
Labels: patch-ver

#999 fix race condition for statuses on export
  app/jobs/bulkrax/export_work_job.rb
Labels: bug, patch-ver

#1001 update the bulkrax factory to support flexible metadata while maintaining non-flexi support
  app/factories/bulkrax/valkyrie_object_factory.rb
Labels: patch-ver

#1000 Revert ObjectFactory#find method returning false instead of nil on missing object
  app/factories/bulkrax/object_factory_interface.rb
Labels: minor-ver

#997 in bootstrap 4+ panel is now card. support both for the moment
  app/assets/stylesheets/bulkrax/import_export.scss
  app/views/bulkrax/entries/show.html.erb
  app/views/bulkrax/exporters/_form.html.erb
  app/views/bulkrax/exporters/edit.html.erb
  app/views/bulkrax/exporters/index.html.erb
  app/views/bulkrax/exporters/new.html.erb
  app/views/bulkrax/exporters/show.html.erb
  app/views/bulkrax/importers/_form.html.erb
  app/views/bulkrax/importers/edit.html.erb
  app/views/bulkrax/importers/index.html.erb
  app/views/bulkrax/importers/new.html.erb
  app/views/bulkrax/importers/show.html.erb
  app/views/bulkrax/importers/upload_corrected_entries.html.erb
Labels: patch-ver
