Repository samvera/bulkrax, pull requests merged in 2024-08, with the labels that each got.

#966 :bug: Refactor: Fix file path access to prevent error
  app/models/bulkrax/importer.rb
Labels: patch-ver

#967 :broom: expands the ability to upload remote_files for valkyrie
  app/factories/bulkrax/valkyrie_object_factory.rb
  db/migrate/20240806161142_add_file_name_to_uploaded_files.rb
Labels: patch-ver

#968 Allow for only thumbnail url in csv
  app/factories/bulkrax/valkyrie_object_factory.rb
Labels: patch-ver

#969 Prevent metadata duplication
  app/models/concerns/bulkrax/has_matchers.rb
Labels: patch-ver, bug-fix

#970 Ability to rerun relationship create job
  app/jobs/bulkrax/create_relationships_job.rb
Labels: patch-ver

#971 Ensure HashWithIndifferentAccess
  app/factories/bulkrax/valkyrie_object_factory.rb
Labels: patch-ver

#972 statuses and max run for pending relationships
  app/jobs/bulkrax/create_relationships_job.rb
  app/models/bulkrax/pending_relationship.rb
  db/migrate/20240823173525_add_error_tracking_to_pending_relationships.rb
Labels: minor-ver

#973 Typo in visibility values doc: embaro -> embargo
  app/parsers/bulkrax/application_parser.rb
Labels: ignore-for-release

#975 Fix for no remote files
  app/factories/bulkrax/valkyrie_object_factory.rb
Labels: ignore-for-release, bug-fix
