Repository samvera/bulkrax, pull requests merged in 2024-01, with the labels that each got.

#895 🎁 Add `Bulkrax.persistence_adapter`
  lib/bulkrax.rb
  lib/bulkrax/engine.rb
  lib/bulkrax/persistence_layer.rb
  lib/bulkrax/persistence_layer/active_fedora_adapter.rb
  lib/bulkrax/persistence_layer/valkyrie_adapter.rb
  spec/lib/bulkrax_spec.rb
Labels: minor-ver

#894 Retry and delete take 2
  app/assets/javascripts/bulkrax/bulkrax.js
  app/controllers/bulkrax/entries_controller.rb
  app/controllers/bulkrax/exporters_controller.rb
  app/controllers/bulkrax/importers_controller.rb
  app/helpers/bulkrax/application_helper.rb
  app/models/bulkrax/importer.rb
  app/views/bulkrax/exporters/show.html.erb
  app/views/bulkrax/importers/_edit_form_buttons.html.erb
  app/views/bulkrax/importers/_edit_item_buttons.html.erb
  app/views/bulkrax/importers/show.html.erb
  app/views/bulkrax/shared/_entries_tab.html.erb
  app/views/bulkrax/shared/_file_set_entries_tab.html.erb
  app/views/bulkrax/shared/_work_entries_tab.html.erb
  config/routes.rb
  spec/test_app/app/helpers/application_helper.rb
Labels: minor-ver

#896 📚 Adding documentation for configuration
  lib/bulkrax.rb
Labels: patch-ver

#898 I897 Bulkrax readiness for Hyku 6 and Hyrax 4 & 5
  app/factories/bulkrax/valkyrie_object_factory.rb
  app/models/concerns/bulkrax/has_matchers.rb
  app/transactions/bulkrax/transactions.rb
  app/transactions/bulkrax/transactions/container.rb
  app/transactions/bulkrax/transactions/steps/add_files.rb
  lib/bulkrax/engine.rb
  lib/generators/bulkrax/templates/config/initializers/bulkrax.rb
  spec/bulkrax/entry_spec_helper_spec.rb
  spec/test_app/app/models/work_resource.rb
  spec/test_app/config/metadata/work_resource.yaml
  spec/test_app/db/schema.rb
  spec/transactions/bulkrax/transactions/container_spec.rb
Labels: patch-ver

#900 ♻️ Extract Bulkrax::FactoryClassFinder
  app/models/bulkrax/csv_collection_entry.rb
  app/models/bulkrax/entry.rb
  app/models/bulkrax/oai_set_entry.rb
  app/models/bulkrax/rdf_collection_entry.rb
  app/models/concerns/bulkrax/file_set_entry_behavior.rb
  app/models/concerns/bulkrax/import_behavior.rb
  app/services/bulkrax/factory_class_finder.rb
  lib/bulkrax.rb
  spec/models/bulkrax/csv_file_set_entry_spec.rb
  spec/models/bulkrax/rdf_file_set_entry_spec.rb
  spec/spec_helper.rb
Labels: patch-ver

#901 🎁 Config option for coercing a factory class name
  app/services/bulkrax/factory_class_finder.rb
  lib/bulkrax.rb
  spec/lib/bulkrax_spec.rb
  spec/services/bulkrax/factory_class_finder_spec.rb
Labels: patch-ver

#902 🧹 Abide by spec file path convention
  spec/bulkrax_spec.rb
Labels: ignore-for-release
