Repository samvera/bulkrax, pull requests merged in 2024-06, with the labels that each got.

#959 Bump version for minor release
  lib/bulkrax/version.rb
Labels: ignore-for-release

#958 add support for downloading the original file
  app/controllers/bulkrax/importers_controller.rb
  app/models/bulkrax/importer.rb
  app/views/bulkrax/importers/show.html.erb
  config/routes.rb
Labels: minor-ver

#960 fix a memory leak when copying large files by using the hyrax uploader
  app/factories/bulkrax/object_factory.rb
Labels: patch-ver

#961 i84 - update visibility label and help text
  app/views/bulkrax/importers/_csv_fields.html.erb
Labels: patch-ver

#963 fix bug from parent addition refactor
  app/factories/bulkrax/object_factory.rb
Labels: patch-ver

#962 i91 - saving nil object caused errors
  app/factories/bulkrax/valkyrie_object_factory.rb
Labels: patch-ver

#964 Delete and redo file sets
  app/jobs/bulkrax/delete_file_set_job.rb
Labels: minor-ver
