Repository samvera/bulkrax, pull requests merged in 2025-01, with the labels that each got.

#1005 hyrax 5 is out but does not support ruby 2.7
  Gemfile
Labels: ignore-for-release

#1004 guard file uploader js to only execute when needed
  app/assets/javascripts/bulkrax/importers.js.erb
Labels: patch-ver

#1006 minor version bump 9.0.1
  lib/bulkrax/version.rb
Labels: ignore-for-release

#1007 :bug: Fix parser field visibility on importer edit form
  Gemfile
  app/assets/javascripts/bulkrax/importers.js.erb
Labels: bug, patch-ver

#1008 minor version bump
  lib/bulkrax/version.rb
Labels: ignore-for-release

#1009 🐛 Fix importing CSV as attachment
  app/parsers/bulkrax/csv_parser.rb
Labels: patch-ver

#1011 🐛 Cleaning up UI on importers show
  app/assets/javascripts/bulkrax/datatables.js
  app/views/bulkrax/importers/show.html.erb
  app/views/bulkrax/shared/_entries_tab.html.erb
  config/locales/bulkrax.en.yml
Labels: patch-ver

#1013 🐛 Fix rerun for entries that came from zips
  app/models/bulkrax/importer.rb
  app/parsers/bulkrax/csv_parser.rb
  spec/fixtures/csv/files/moon.jpg
Labels: patch-ver

#1014 🐛 Fix `#importer_unzip_path` logic
  app/models/bulkrax/importer.rb
  app/parsers/bulkrax/application_parser.rb
Labels: patch-ver
